[package]
name = "exempi-sys"
version = "2.5.0"
authors = ["Hubert Figuière <hub@figuiere.net>"]
license = "BSD-2-Clause"
links = "exempi"
build = "build.rs"
description = "Unsafe Rust bindings to Exempi 2.4. Part of exempi-rs."
keywords = ["xmp", "metadata"]
repository = "https://github.com/hfiguiere/exempi-rs"
homepage = "https://libopenraw.freedesktop.org/exempi/"

[dependencies]
libc = "0.2"
libz-sys = {version = "1.0.25", features=["static"] }
expat-sys = "2.1.6"

[build-dependencies]
pkg-config = "0.3"
